In [5]:
import pandas as pd

In [6]:
tabla = pd.read_csv('C:/Users/cti9264/Documents/Vscode Python/ventasTotales.csv',skiprows=5,sep=';')
tabla.head()

,Fecha,Vendedor,Región,Artículo,Categoría,Unidades,Ganancia
0,1/1/2016,Steve Ashton,Norte,Medias Femeninas,Vestimenta,6,"18,00"
1,1/1/2016,Trevor Snodgrass,Oeste,Chocolate,Comestibles,8,"3,84"
2,1/1/2016,Sarah Bond,Sur,Gorras,Vestimenta,3,"6,30"
3,1/1/2016,Desmond Delaney,Sur,Sánguche de Queso,Comestibles,9,"14,40"
4,1/1/2016,Desmond Delaney,Este,Chocolate,Comestibles,14,"6,72"

In [7]:
print(tabla.Vendedor == 'Sarah Bond')

0      False
1      False
2       True
3      False
4      False
       ...
455     True
456    False
457    False
458    False
459    False
Name: Vendedor, Length: 460, dtype: bool

In [10]:
cat = tabla[(tabla.Vendedor =='Sarah Bond')&((tabla.Categoría=='Vestimenta')|(tabla.Categoría == 'Comestibles'))]
cat

,Fecha,Vendedor,Región,Artículo,Categoría,Unidades,Ganancia
2,1/1/2016,Sarah Bond,Sur,Gorras,Vestimenta,3,"6,30"
9,1/1/2016,Sarah Bond,Este,Caramelos,Comestibles,15,"9,00"
23,2/1/2016,Sarah Bond,Norte,Bufanda,Vestimenta,4,"11,00"
48,4/1/2016,Sarah Bond,Este,Shorts,Vestimenta,2,"9,80"
49,4/1/2016,Sarah Bond,Norte,Shorts,Vestimenta,12,"58,80"
58,4/1/2016,Sarah Bond,Este,Bufanda,Vestimenta,14,"38,50"
62,5/1/2016,Sarah Bond,Norte,Cerveza,Comestibles,3,"1,20"
65,5/1/2016,Sarah Bond,Norte,Pan,Comestibles,3,"1,20"
85,6/1/2016,Sarah Bond,Norte,Gorras,Vestimenta,9,"18,90"
89,6/1/2016,Sarah Bond,Sur,Cerveza,Comestibles,15,"6,00"
104,7/1/2016,Sarah Bond,Este,Calcetines,Vestimenta,13,"29,25"
106,7/1/2016,Sarah Bond,Oeste,Calcetines,Vestimenta,8,"18,00"
108,7/1/2016,Sarah Bond,Norte,Pan,Comestibles,4,"1,60"
123,8/1/2016,Sarah Bond,Sur,Bufanda,Vestimenta,4,"11,00"
124,8/1/2016,Sarah Bond,Sur,Sandalias,Vestimenta,15,"157,50"
126,8/1/2016,Sarah Bond,Norte,Calcetines,Vestimenta,3,"6,75"
127,8/1/2016,Sarah Bond,Norte,Sánguche de Queso,Comestibles,14,"22,40"
134,9/1/2016,Sarah Bond,Oeste,Pepinillo,Comestibles,2,"0,60"
136,9/1/2016,Sarah Bond,Sur,Soda,Comestibles,11,"7,04"
137,9/1/2016,Sarah Bond,Este,Bufanda,Vestimenta,3,"8,25"
147,10/1/2016,Sarah Bond,Este,Medias Femeninas,Vestimenta,4,"12,00"
170,11/1/2016,Sarah Bond,Este,Gorras,Vestimenta,9,"18,90"
186,12/1/2016,Sarah Bond,Este,Gorras,Vestimenta,11,"23,10"
188,13/1/2016,Sarah Bond,Oeste,Calcetines,Vestimenta,1,"2,25"
199,13/1/2016,Sarah Bond,Norte,Cerveza,Comestibles,11,"4,40"
202,14/1/2016,Sarah Bond,Sur,Pan,Comestibles,6,"2,40"
213,14/1/2016,Sarah Bond,Este,Shorts,Vestimenta,9,"44,10"
215,15/1/2016,Sarah Bond,Oeste,Chocolate,Comestibles,6,"2,88"
216,15/1/2016,Sarah Bond,Sur,Pan,Comestibles,7,"2,80"
217,15/1/2016,Sarah Bond,Sur,Sudadera,Vestimenta,1,"6,00"
222,15/1/2016,Sarah Bond,Norte,Chocolate,Comestibles,12,"5,76"
230,15/1/2016,Sarah Bond,Sur,Chocolate,Comestibles,4,"1,92"
252,17/1/2016,Sarah Bond,Sur,Soda,Comestibles,10,"6,40"
255,17/1/2016,Sarah Bond,Norte,Medias Femeninas,Vestimenta,12,"36,00"
268,18/1/2016,Sarah Bond,Sur,Pan,Comestibles,12,"4,80"
270,18/1/2016,Sarah Bond,Norte,Chocolate,Comestibles,5,"2,40"
277,19/1/2016,Sarah Bond,Sur,Pan,Comestibles,12,"4,80"
283,19/1/2016,Sarah Bond,Este,Chocolate,Comestibles,8,"3,84"
287,19/1/2016,Sarah Bond,Oeste,Soda,Comestibles,13,"8,32"
289,19/1/2016,Sarah Bond,Este,Sudadera,Vestimenta,1,"6,00"
294,20/1/2016,Sarah Bond,Sur,Pepinillo,Comestibles,2,"0,60"
302,20/1/2016,Sarah Bond,Norte,Pepinillo,Comestibles,11,"3,30"
303,20/1/2016,Sarah Bond,Norte,Caramelos,Comestibles,15,"9,00"
318,21/1/2016,Sarah Bond,Norte,Calcetines,Vestimenta,5,"11,25"
331,22/1/2016,Sarah Bond,Oeste,Sandalias,Vestimenta,2,"21,00"
337,23/1/2016,Sarah Bond,Este,Pepinillo,Comestibles,6,"1,80"
351,24/1/2016,Sarah Bond,Este,Shorts,Vestimenta,6,"29,40"
365,26/1/2016,Sarah Bond,Sur,Chocolate,Comestibles,13,"6,24"
374,26/1/2016,Sarah Bond,Este,Cerveza,Comestibles,8,"3,20"
379,27/1/2016,Sarah Bond,Este,Cerveza,Comestibles,5,"2,00"
409,28/1/2016,Sarah Bond,Este,Sánguche de Queso,Comestibles,7,"11,20"
416,28/1/2016,Sarah Bond,Este,Sánguche de Queso,Comestibles,5,"8,00"
418,29/1/2016,Sarah Bond,Norte,Caramelos,Comestibles,9,"5,40"
420,29/1/2016,Sarah Bond,Este,Gorras,Vestimenta,13,"27,30"
426,29/1/2016,Sarah Bond,Este,Gorras,Vestimenta,7,"14,70"
443,31/1/2016,Sarah Bond,Sur,Calcetines,Vestimenta,7,"15,75"
455,31/1/2016,Sarah Bond,Sur,Bufanda,Vestimenta,6,"16,50"

In [12]:
c = cat.groupby(['Artículo','Categoría','Región']).size()
c

Artículo           Categoría    Región
Bufanda            Vestimenta   Este      2
                                Norte     1
                                Sur       2
Calcetines         Vestimenta   Este      1
                                Norte     2
                                Oeste     2
                                Sur       1
Caramelos          Comestibles  Este      1
                                Norte     2
Cerveza            Comestibles  Este      2
                                Norte     2
                                Sur       1
Chocolate          Comestibles  Este      1
                                Norte     2
                                Oeste     1
                                Sur       2
Gorras             Vestimenta   Este      4
                                Norte     1
                                Sur       1
Medias Femeninas   Vestimenta   Este      1
                                Norte     1
Pan                Comestibles  Norte     2
                                Sur       4
Pepinillo          Comestibles  Este      1
                                Norte     1
                                Oeste     1
                                Sur       1
Sandalias          Vestimenta   Oeste     1
                                Sur       1
Shorts             Vestimenta   Este      3
                                Norte     1
Soda               Comestibles  Oeste     1
                                Sur       2
Sudadera           Vestimenta   Este      1
                                Sur       1
Sánguche de Queso  Comestibles  Este      2
                                Norte     1
dtype: int64

In [14]:
df = c.unstack('Región')
df

Región                         Este  Norte  Oeste  Sur
Artículo          Categoría
Bufanda           Vestimenta    2.0    1.0    NaN  2.0
Calcetines        Vestimenta    1.0    2.0    2.0  1.0
Caramelos         Comestibles   1.0    2.0    NaN  NaN
Cerveza           Comestibles   2.0    2.0    NaN  1.0
Chocolate         Comestibles   1.0    2.0    1.0  2.0
Gorras            Vestimenta    4.0    1.0    NaN  1.0
Medias Femeninas  Vestimenta    1.0    1.0    NaN  NaN
Pan               Comestibles   NaN    2.0    NaN  4.0
Pepinillo         Comestibles   1.0    1.0    1.0  1.0
Sandalias         Vestimenta    NaN    NaN    1.0  1.0
Shorts            Vestimenta    3.0    1.0    NaN  NaN
Soda              Comestibles   NaN    NaN    1.0  2.0
Sudadera          Vestimenta    1.0    NaN    NaN  1.0
Sánguche de Queso Comestibles   2.0    1.0    NaN  NaN

In [15]:
df.stack()

Artículo           Categoría    Región
Bufanda            Vestimenta   Este      2.0
                                Norte     1.0
                                Sur       2.0
Calcetines         Vestimenta   Este      1.0
                                Norte     2.0
                                Oeste     2.0
                                Sur       1.0
Caramelos          Comestibles  Este      1.0
                                Norte     2.0
Cerveza            Comestibles  Este      2.0
                                Norte     2.0
                                Sur       1.0
Chocolate          Comestibles  Este      1.0
                                Norte     2.0
                                Oeste     1.0
                                Sur       2.0
Gorras             Vestimenta   Este      4.0
                                Norte     1.0
                                Sur       1.0
Medias Femeninas   Vestimenta   Este      1.0
                                Norte     1.0
Pan                Comestibles  Norte     2.0
                                Sur       4.0
Pepinillo          Comestibles  Este      1.0
                                Norte     1.0
                                Oeste     1.0
                                Sur       1.0
Sandalias          Vestimenta   Oeste     1.0
                                Sur       1.0
Shorts             Vestimenta   Este      3.0
                                Norte     1.0
Soda               Comestibles  Oeste     1.0
                                Sur       2.0
Sudadera           Vestimenta   Este      1.0
                                Sur       1.0
Sánguche de Queso  Comestibles  Este      2.0
                                Norte     1.0
dtype: float64

In [16]:
df

Región                         Este  Norte  Oeste  Sur
Artículo          Categoría
Bufanda           Vestimenta    2.0    1.0    NaN  2.0
Calcetines        Vestimenta    1.0    2.0    2.0  1.0
Caramelos         Comestibles   1.0    2.0    NaN  NaN
Cerveza           Comestibles   2.0    2.0    NaN  1.0
Chocolate         Comestibles   1.0    2.0    1.0  2.0
Gorras            Vestimenta    4.0    1.0    NaN  1.0
Medias Femeninas  Vestimenta    1.0    1.0    NaN  NaN
Pan               Comestibles   NaN    2.0    NaN  4.0
Pepinillo         Comestibles   1.0    1.0    1.0  1.0
Sandalias         Vestimenta    NaN    NaN    1.0  1.0
Shorts            Vestimenta    3.0    1.0    NaN  NaN
Soda              Comestibles   NaN    NaN    1.0  2.0
Sudadera          Vestimenta    1.0    NaN    NaN  1.0
Sánguche de Queso Comestibles   2.0    1.0    NaN  NaN

In [17]:
df.unstack()

Región                   Este                  Norte                  Oeste  \
Categoría         Comestibles Vestimenta Comestibles Vestimenta Comestibles
Artículo
Bufanda                   NaN        2.0         NaN        1.0         NaN
Calcetines                NaN        1.0         NaN        2.0         NaN
Caramelos                 1.0        NaN         2.0        NaN         NaN
Cerveza                   2.0        NaN         2.0        NaN         NaN
Chocolate                 1.0        NaN         2.0        NaN         1.0
Gorras                    NaN        4.0         NaN        1.0         NaN
Medias Femeninas          NaN        1.0         NaN        1.0         NaN
Pan                       NaN        NaN         2.0        NaN         NaN
Pepinillo                 1.0        NaN         1.0        NaN         1.0
Sandalias                 NaN        NaN         NaN        NaN         NaN
Shorts                    NaN        3.0         NaN        1.0         NaN
Soda                      NaN        NaN         NaN        NaN         1.0
Sudadera                  NaN        1.0         NaN        NaN         NaN
Sánguche de Queso         2.0        NaN         1.0        NaN         NaN

Región                               Sur
Categoría         Vestimenta Comestibles Vestimenta
Artículo
Bufanda                  NaN         NaN        2.0
Calcetines               2.0         NaN        1.0
Caramelos                NaN         NaN        NaN
Cerveza                  NaN         1.0        NaN
Chocolate                NaN         2.0        NaN
Gorras                   NaN         NaN        1.0
Medias Femeninas         NaN         NaN        NaN
Pan                      NaN         4.0        NaN
Pepinillo                NaN         1.0        NaN
Sandalias                1.0         NaN        1.0
Shorts                   NaN         NaN        NaN
Soda                     NaN         2.0        NaN
Sudadera                 NaN         NaN        1.0
Sánguche de Queso        NaN         NaN        NaN